version = "3.10.7"
runner.dialect = "scala213"

maxColumn = 120
assumeStandardLibraryStripMargin = true
lineEndings = unix

align {
  preset = most
  multiline = false
}

continuationIndent {
  defnSite = 2
}

docstrings {
  style = AsteriskSpace
  blankFirstLine = yes
}

danglingParentheses {
  preset = true
}

newlines {
  annotation = true
  alwaysBeforeMultilineDef = false
  beforeCurlyLambdaParams = multilineWithCaseOnly
  selectChains.classicCanStartWithBraceApply = false
}

project.excludeFilters = [
  "macros/*",
  "src/test/scala/intellij/testfixtures/*",
]

rewrite {
  rules = [SortImports, RedundantBraces]
  redundantBraces.generalExpressions = false
  tokens = {
    "⇒": "=>"
    "→": "->"
    "←": "<-"
  }
}