name: CI

on:
  push:
    branches:
      - idea251.x
      - idea252.x
      - idea253.x
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adoptium:21
          apps: sbt sbtn

      - uses: coursier/cache-action@v6

      - name: Fetch Dependencies
        run: sbt +update

        # Just to check that plugin can be packaged for release
        # TODO: remove copying of searchableOptions, they should be generated automatically by packageArtifactZip
      - name: Try packaging
        shell: bash
        run: |
          sbt clean
          mkdir -p "$GITHUB_WORKSPACE/target/searchableOptions"
          cp -r "$GITHUB_WORKSPACE/src/main/resources/searchableOptions" "$GITHUB_WORKSPACE/target/"
          sbt packageArtifact && sbt packageArtifactZip

      - name: Run tests
        run: sbt test
        shell: bash

