name: CI
on:
  push:
    branches: [ idea201.x, idea202.x, idea203.x ]
  pull_request:
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.8"
      - name: Run tests
        run: sbt test
