name: CI

on:
  push:
    branches:
      - idea243.x
      - idea251.x
      - idea252.x
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      SBT_IDEA_GEN_SEARCHABLE_OPTIONS_INDEX_DISCARD_OUTPUT: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adoptium:1.17
          apps: sbtn sbt

      - uses: coursier/cache-action@v6
        id: coursier-cache

      - name: Fetch Dependencies
        if: steps.coursier-cache.outputs.cache-hit-coursier != 'true'
        run: sbt +update

      - name: Try packaging
        # Just to check that plugin can be packaged for release
        run: sbt clean && sbt packageArtifact && sbt packZipVerbose

      - name: Run tests
        run: sbt test
        shell: bash

      - name: Show folder
        if: always()
        continue-on-error: true
        run: |
          ls /home/runner/.zio-intellijPluginIC/sdk/252.25557.77/ || true

      - name: Show plugins_index
        if: always()
        continue-on-error: true
        run: |
          cat /home/runner/.zio-intellijPluginIC/sdk/252.25557.77/plugins_index.xml || true

      - name: Show system
        if: always()
        continue-on-error: true
        run: |
          ls /home/runner/.zio-intellijPluginIC/config
