name: CI

on:
  push:
    branches:
      - idea242.x
      - idea243.x
      - idea251.x
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adoptium:1.17
          apps: sbtn sbt

      - uses: coursier/cache-action@v6
        id: coursier-cache

      - name: Fetch Dependencies
        if: steps.coursier-cache.outputs.cache-hit-coursier != 'true'
        run: sbt +update

      - name: Run tests
        run: sbt test
        shell: bash

